name: Run JUnit tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17  # Cập nhật phiên bản JDK ở đây
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Sử dụng JDK 17
        distribution: 'temurin'  # Chọn distribution

    - name: Build with Maven
      run: mvn clean install

    - name: Run JUnit tests
      run: mvn test
